import type {
  User,
  PatientCase,
  Medicine,
  Pharmacy,
  PrebookingRequest,
} from "./types"

export const mockUsers: User[] = [
  {
    id: "hw-1",
    name: "Priya Sharma",
    email: "priya@ruralcare.in",
    role: "health_worker",
    phone: "+91 98765 43210",
  },
  {
    id: "hw-2",
    name: "Anjali Kaur",
    email: "anjali@ruralcare.in",
    role: "health_worker",
    phone: "+91 98765 43211",
  },
  {
    id: "doc-1",
    name: "Dr. Rajesh Kumar",
    email: "rajesh@ruralcare.in",
    role: "doctor",
    phone: "+91 98765 43220",
  },
  {
    id: "doc-2",
    name: "Dr. Meena Singh",
    email: "meena@ruralcare.in",
    role: "doctor",
    phone: "+91 98765 43221",
  },
  {
    id: "pharm-1",
    name: "Gurpreet Singh",
    email: "gurpreet@ruralcare.in",
    role: "pharmacist",
    phone: "+91 98765 43230",
  },
]

export const mockPharmacies: Pharmacy[] = [
  {
    id: "pharmacy-1",
    name: "Jan Aushadhi Kendra - Moga",
    address: "Main Market, Moga, Punjab",
    phone: "+91 98765 11111",
  },
  {
    id: "pharmacy-2",
    name: "Rural Health Pharmacy - Bathinda",
    address: "Civil Hospital Road, Bathinda, Punjab",
    phone: "+91 98765 22222",
  },
  {
    id: "pharmacy-3",
    name: "Gram Seva Medical Store - Sangrur",
    address: "Bus Stand, Sangrur, Punjab",
    phone: "+91 98765 33333",
  },
]

export const mockMedicines: Medicine[] = [
  {
    id: "med-1",
    name: "Paracetamol 500mg",
    quantity: 150,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "med-2",
    name: "Paracetamol 500mg",
    quantity: 0,
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    updatedAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "med-3",
    name: "Paracetamol 500mg",
    quantity: 75,
    pharmacyId: "pharmacy-3",
    pharmacyName: "Gram Seva Medical Store - Sangrur",
    updatedAt: "2026-02-03T11:00:00Z",
  },
  {
    id: "med-4",
    name: "Amoxicillin 250mg",
    quantity: 50,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "med-5",
    name: "Amoxicillin 250mg",
    quantity: 30,
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    updatedAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "med-6",
    name: "Metformin 500mg",
    quantity: 200,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "med-7",
    name: "Metformin 500mg",
    quantity: 0,
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    updatedAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "med-8",
    name: "ORS Sachets",
    quantity: 500,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "med-9",
    name: "ORS Sachets",
    quantity: 300,
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    updatedAt: "2026-02-03T09:00:00Z",
  },
  {
    id: "med-10",
    name: "ORS Sachets",
    quantity: 0,
    pharmacyId: "pharmacy-3",
    pharmacyName: "Gram Seva Medical Store - Sangrur",
    updatedAt: "2026-02-03T11:00:00Z",
  },
  {
    id: "med-11",
    name: "Cetirizine 10mg",
    quantity: 100,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
  {
    id: "med-12",
    name: "Ibuprofen 400mg",
    quantity: 80,
    pharmacyId: "pharmacy-1",
    pharmacyName: "Jan Aushadhi Kendra - Moga",
    updatedAt: "2026-02-03T10:00:00Z",
  },
]

export const mockCases: PatientCase[] = [
  {
    id: "case-1",
    patientName: "Harjit Singh",
    patientAge: 45,
    patientGender: "Male",
    patientPhone: "+91 99876 54321",
    patientVillage: "Khanna Village",
    symptoms: ["Fever", "Body ache", "Headache"],
    vitals: {
      temperature: 101.5,
      bloodPressure: "130/85",
      pulseRate: 88,
      oxygenLevel: 96,
    },
    additionalNotes: "Symptoms started 2 days ago. No known allergies.",
    aiRiskLevel: "Medium",
    status: "pending",
    healthWorkerId: "hw-1",
    healthWorkerName: "Priya Sharma",
    createdAt: "2026-02-03T08:30:00Z",
  },
  {
    id: "case-2",
    patientName: "Kulwant Kaur",
    patientAge: 62,
    patientGender: "Female",
    patientPhone: "+91 99876 54322",
    patientVillage: "Moga Town",
    symptoms: ["Chest pain", "Shortness of breath", "Dizziness"],
    vitals: {
      temperature: 98.6,
      bloodPressure: "160/100",
      pulseRate: 102,
      oxygenLevel: 92,
    },
    additionalNotes: "History of hypertension. Taking BP medication.",
    aiRiskLevel: "High",
    status: "pending",
    healthWorkerId: "hw-1",
    healthWorkerName: "Priya Sharma",
    createdAt: "2026-02-03T09:15:00Z",
  },
  {
    id: "case-3",
    patientName: "Ravi Kumar",
    patientAge: 28,
    patientGender: "Male",
    patientPhone: "+91 99876 54323",
    patientVillage: "Sangrur District",
    symptoms: ["Common cold", "Runny nose", "Mild cough"],
    vitals: {
      temperature: 99.2,
      bloodPressure: "120/80",
      pulseRate: 72,
      oxygenLevel: 98,
    },
    additionalNotes: "Seasonal change symptoms.",
    aiRiskLevel: "Low",
    status: "reviewed",
    decision: "home_care",
    medicalAdvice: "Rest and hydration. Take steam inhalation twice daily.",
    prescription: "Paracetamol 500mg - 1 tablet thrice daily after meals for 3 days. Cetirizine 10mg - 1 tablet at night for 5 days.",
    healthWorkerId: "hw-2",
    healthWorkerName: "Anjali Kaur",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Kumar",
    createdAt: "2026-02-02T14:00:00Z",
    reviewedAt: "2026-02-02T16:30:00Z",
  },
  {
    id: "case-4",
    patientName: "Simran Kaur",
    patientAge: 8,
    patientGender: "Female",
    patientPhone: "+91 99876 54324",
    patientVillage: "Bathinda Rural",
    symptoms: ["High fever", "Vomiting", "Loose motions"],
    vitals: {
      temperature: 103.2,
      bloodPressure: "90/60",
      pulseRate: 110,
      oxygenLevel: 95,
    },
    additionalNotes: "Child is weak. Not eating since yesterday.",
    aiRiskLevel: "High",
    status: "reviewed",
    decision: "scheduled_visit",
    medicalAdvice: "Needs IV fluids. Schedule hospital visit within 24 hours.",
    prescription: "ORS after every loose motion. Paracetamol syrup for fever.",
    healthWorkerId: "hw-1",
    healthWorkerName: "Priya Sharma",
    doctorId: "doc-2",
    doctorName: "Dr. Meena Singh",
    doctorRiskOverride: "High",
    createdAt: "2026-02-01T11:00:00Z",
    reviewedAt: "2026-02-01T13:00:00Z",
  },
]

export const mockPrebookings: PrebookingRequest[] = [
  {
    id: "pb-1",
    medicineId: "med-2",
    medicineName: "Paracetamol 500mg",
    requestedQuantity: 30,
    patientName: "Manjit Singh",
    patientPhone: "+91 99876 11111",
    healthWorkerId: "hw-1",
    healthWorkerName: "Priya Sharma",
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    status: "pending",
    createdAt: "2026-02-03T10:30:00Z",
  },
  {
    id: "pb-2",
    medicineId: "med-7",
    medicineName: "Metformin 500mg",
    requestedQuantity: 60,
    patientName: "Balwinder Kaur",
    patientPhone: "+91 99876 22222",
    healthWorkerId: "hw-2",
    healthWorkerName: "Anjali Kaur",
    pharmacyId: "pharmacy-2",
    pharmacyName: "Rural Health Pharmacy - Bathinda",
    status: "confirmed",
    expectedAvailabilityDate: "2026-02-05",
    createdAt: "2026-02-02T14:00:00Z",
    respondedAt: "2026-02-02T16:00:00Z",
  },
  {
    id: "pb-3",
    medicineId: "med-10",
    medicineName: "ORS Sachets",
    requestedQuantity: 20,
    patientName: "Gurpreet Singh",
    patientPhone: "+91 99876 33333",
    healthWorkerId: "hw-1",
    healthWorkerName: "Priya Sharma",
    pharmacyId: "pharmacy-3",
    pharmacyName: "Gram Seva Medical Store - Sangrur",
    status: "pending",
    createdAt: "2026-02-03T09:00:00Z",
  },
]
